version: '3.2'
services:
  spacechop:
    command: npm run test:ci
    build:
      cache_from: 
        - spacechop:latest
      args:
        env: development
    volumes:
      - ./coverage:/src/coverage
