version: '3.2'
services:
  spacechop:
    command: npm run develop
    volumes:
      - ./src:/src/app
      - ./benchmarking/benchmarking-config.yml:/config.yml
    build:
      args:
        env: development

  nginx:
    image: nginx
    volumes:
      - ./benchmarking/assets:/usr/share/nginx/html
