paths:
  - /images/:preset/:image

sources:
  - volume:
      root: /src/app/test/assets/:image

presets:
  t_720:
    steps:
      - $crop:
          width: 720
          gravity: center

      - $format:
          type: jpeg

      - $compress:
          quality: 92
          lossy: true
