path: /images/:preset/:imageName

sources:
  - s3:
    secret: xxxx
    prefix: zzz/zzz
    bucket: yyy

  - http:
    root: https://example.com/images/lol

presets:
  t_720:
    steps:
      - crop:
        width: 720
        mode: crop
        gravity: center
      
      - compress:
        lossy: true
        quality: 92