paths: 
  - /:preset/:image

sources:
  - http:
      root: http://nginx/:image

presets:
  t_720:
    steps:
      - $crop:
          width: 720

      - $format:
          type: jpeg

      - $compress:
          quality: 92
          lossy: true
